version: '2.3'

services:
 ham-web:
  image: kevlee/ham-web-rpi
  restart: unless-stopped
  container_name: ham-web
  ports:
   - 192.168.1.193:80:80
 ham-api:
  image: kevlee/ham-api-rpi
  restart: unless-stopped
  container_name: ham-api
  ports:
   - 192.168.1.194:80:80
  privileged: true
  devices:
   - '/dev:/dev'
  env_file:
   ./API/.env.production
  depends_on:
   - db
 db:
  image: hypriot/rpi-mysql
  container_name: ham-db
  restart: unless-stopped
  env_file:
   ./API/.env.production
  ports:
   - 192.168.1.195:3306:3306
  expose:
   - 3306
  volumes:
   - my-db:/var/lib/mysql

volumes:
  my-db: