FROM arm32v7/node as build-stage
ENV TOOL_NODE_FLAGS="--max-old-space-size=2048"
ENV npm_config_arch=arm32v7
WORKDIR /home-alive-me
COPY package*.json ./
RUN npm install
COPY ./ .
RUN npm run build

FROM arm32v7/nginx as production-stage
RUN mkdir /app
COPY --from=build-stage /home-alive-me/dist /app
COPY nginx.conf /etc/nginx/nginx.conf