-- MySQL Workbench Synchronization
-- Generated: 2020-11-05 17:23
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: temin

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

ALTER SCHEMA `homealiveme`  DEFAULT CHARACTER SET utf8  DEFAULT COLLATE utf8_general_ci ;

CREATE TABLE IF NOT EXISTS `homealiveme`.`nodes` (
  `nodehexcode` VARCHAR(32) NOT NULL,
  `nodeid` INT(11) NOT NULL,
  PRIMARY KEY (`nodehexcode`),
  UNIQUE INDEX `nodeid_UNIQUE` (`nodeid` ASC) VISIBLE,
  UNIQUE INDEX `nodehexcode_UNIQUE` (`nodehexcode` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
